export const SHOW_TRADE_COMPLETED_MODAL = "SHOW_TRADE_COMPLETED_MODAL";
export const HIDE_TRADE_COMPLETED_MODAL = "HIDE_TRADE_COMPLETED_MODAL";

export const SHOW_FIDUCIARY_CREATION_MODAL = "SHOW_FIDUCIARY_CREATION_MODAL";
export const HIDE_FIDUCIARY_CREATION_MODAL = "HIDE_FIDUCIARY_CREATION_MODAL";

export const SET_TOKEN_VAULT_TABLE_CONTEXT = "SET_TOKEN_VAULT_TABLE_CONTEXT";

export const FETCH_FIDUCIARY_PRODUCTS = "FETCH_FIDUCIARY_PRODUCTS";
export const FETCH_FIDUCIARY_PRODUCTS_SUCCESS =
  "FETCH_FIDUCIARY_PRODUCTS_SUCCESS";
export const FETCH_FIDUCIARY_PRODUCTS_ERROR = "FETCH_FIDUCIARY_PRODUCTS_ERROR";
export const SET_FILTERS_FIDUCIARY_PRODUCTS = "SET_FILTERS_FIDUCIARY_PRODUCTS";
export const UPDATE_FIDUCIARY_DEPOSIT_STATUS =
  "UPDATE_FIDUCIARY_DEPOSIT_STATUS";
export const UPDATE_FIDUCIARY_DEPOSIT_PAUSED_CONTRACTS =
  "UPDATE_FIDUCIARY_DEPOSIT_PAUSED_CONTRACTS";

export const EXPIRE_FIDUCIARY_DEPOSIT = "EXPIRE_FIDUCIARY_DEPOSIT";
export const EXPIRE_FIDUCIARY_DEPOSIT_SUCCESS =
  "EXPIRE_FIDUCIARY_DEPOSIT_SUCCESS";
export const EXPIRE_FIDUCIARY_DEPOSIT_ERROR = "EXPIRE_FIDUCIARY_DEPOSIT_ERROR";

export const EXPIRE_EARLY_FIDUCIARY_DEPOSIT = "EXPIRE_EARLY_FIDUCIARY_DEPOSIT";
export const EXPIRE_EARLY_FIDUCIARY_DEPOSIT_SUCCESS =
  "EXPIRE_EARLY_FIDUCIARY_DEPOSIT_SUCCESS";
export const EXPIRE_EARLY_FIDUCIARY_DEPOSIT_ERROR =
  "EXPIRE_EARLY_FIDUCIARY_DEPOSIT_ERROR";

export const SET_EXPIRE_EARLY_FD_MODAL_VISIBLE =
  "SET_EXPIRE_EARLY_FD_MODAL_VISIBLE";

export const SEIZE_FIDUCIARY_DEPOSIT = "SEIZE_FIDUCIARY_DEPOSIT";
export const SEIZE_FIDUCIARY_DEPOSIT_SUCCESS =
  "SEIZE_FIDUCIARY_DEPOSIT_SUCCESS";
export const SEIZE_FIDUCIARY_DEPOSIT_ERROR = "SEIZE_FIDUCIARY_DEPOSIT_ERROR";

export const FREEZE_FIDUCIARY_DEPOSIT = "FREEZE_FIDUCIARY_DEPOSIT";
export const FREEZE_FIDUCIARY_DEPOSIT_SUCCESS =
  "FREEZE_FIDUCIARY_DEPOSIT_SUCCESS";
export const FREEZE_FIDUCIARY_DEPOSIT_ERROR = "FREEZE_FIDUCIARY_DEPOSIT_ERROR";

export const ISSUE_FIDUCIARY = "ISSUE_FIDUCIARY";
export const ISSUE_FIDUCIARY_SUCCESS = "ISSUE_FIDUCIARY_SUCCESS";
export const ISSUE_FIDUCIARY_ERROR = "ISSUE_FIDUCIARY_ERROR";

export const CO_ISSUE_FIDUCIARY_NEEDED = "CO_ISSUE_FIDUCIARY_NEEDED";

export const SET_COMPLETE_ISSUNACE_FIDUCIARY_LOCK =
  "SET_COMPLETE_ISSUNACE_FIDUCIARY_LOCK";

export const COMPLETE_ISSUNACE_FIDUCIARY = "COMPLETE_ISSUNACE_FIDUCIARY";
export const COMPLETE_ISSUNACE_FIDUCIARY_SUCCESS =
  "COMPLETE_ISSUNACE_FIDUCIARY_SUCCESS";
export const COMPLETE_ISSUNACE_FIDUCIARY_ERROR =
  "COMPLETE_ISSUNACE_FIDUCIARY_ERROR";

export const FETCH_FX_DOCU = "FETCH_FX_DOCU";
export const FETCH_FX_DOCU_SUCCESS = "FETCH_FX_DOCU_SUCCESS";
export const FETCH_FX_DOCU_ERROR = "FETCH_FX_DOCU_ERROR";
export const SET_FILTERS_FX_DOCU = "SET_FILTERS_FX_DOCU";
export const SET_SORTING_FX_DOCU = "SET_SORTING_FX_DOCU";
export const UPDATE_FX_DOCU_STATUS = "UPDATE_FX_DOCU_STATUS";
export const UPDATE_FX_DOCU_PAUSED_CONTRACTS =
  "UPDATE_FX_DOCU_PAUSED_CONTRACTS";
export const RECALCULATE_TOTALS_FX_DOCU = "RECALCULATE_TOTALS_FX_DOCU";

export const FX_DOCU_ALLOW_TRANSFER_MODAL = "FX_DOCU_ALLOW_TRANSFER_MODAL";
export const FX_DOCU_TRANSFER = "FX_DOCU_TRANSFER";
export const FX_DOCU_TRANSFER_SUCCESS = "FX_DOCU_TRANSFER_SUCCESS";
export const FX_DOCU_TRANSFER_ERROR = "FX_DOCU_TRANSFER_ERROR";

export const FX_DOCU_EXPIRE_MODAL = "FX_DOCU_EXPIRE_MODAL";
export const FX_DOCU_EXPIRE = "FX_DOCU_EXPIRE";
export const FX_DOCU_EXPIRE_SUCCESS = "FX_DOCU_EXPIRE_SUCCESS";
export const FX_DOCU_EXPIRE_ERROR = "FX_DOCU_EXPIRE_ERROR";

export const FX_DOCU_DETAILS_MODAL = "FX_DOCU_DETAILS_MODAL";

export const FX_DOCU_JSON_DETAILS_MODAL = "FX_DOCU_JSON_DETAILS_MODAL";

export const FX_DOCU_CREATE_MODAL = "FX_DOCU_CREATE_MODAL";

export const FX_DOCU_ISSUE = "FX_DOCU_ISSUE";
export const FX_DOCU_ISSUE_SUCCESS = "FX_DOCU_ISSUE_SUCCESS";
export const FX_DOCU_ISSUE_ERROR = "FX_DOCU_ISSUE_ERROR";
export const FX_DOCU_ISSUE_RESET = "FX_DOCU_ISSUE_RESET";

export const FX_DOCU_CO_ISSUE_REQUIRED = "FX_DOCU_CO_ISSUE_REQUIRED";
export const FX_DOCU_CO_ISSUE = "FX_DOCU_CO_ISSUE";
export const FX_DOCU_CO_ISSUE_SUCCESS = "FX_DOCU_CO_ISSUE_SUCCESS";
export const FX_DOCU_CO_ISSUE_ERROR = "FX_DOCU_CO_ISSUE_ERROR";
